---
title: Publications
---

<h4>Forthcoming</h4>

<a href="https://github.com/ctesta01/covid.gradient.estimation/raw/main/manuscript/manuscript.pdf">
Understanding Complex Patterns in Social, Geographic, and Economic Inequities in COVID-19
Mortality at the County Level in the US Using Generalized Additive Models
</a>
<div class='details'>
<b> Testa C</b>. Preprint on arXiv.
</div>

<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3933453">
The evolving roles of US political partisanship and social vulnerability in the COVID-19 pandemic from February 2020–February 2021
</a>
<div class='details'>
Kaashoek J, <b>Testa C</b>, Chen JT, Stolerman L, Krieger N, Hanage WP, Santillana M. PLOS Global Public Health.
</div>

<a href="https://research-information.bris.ac.uk/en/publications/use-of-incorrect-and-correct-methods-to-account-for-age-in-studie">
Use of incorrect and correct methods to account for age in studies on epigenetic accelerated aging: implications and recommendations for best practices
</a>
<div class='details'>
Krieger N, Chen JT, <b>Testa C</b>, Chen JT, Diez Roux AV, Tilling K, Watkins SH, Simpkin AJ, Suderman MJ, Davey Smith G, De Vivo I, Waterman PD, Relton CL. American Journal of Epidemiology.
</div>

<a href="">Tabby2: A User-Friendly Web Tool for Forecasting State-Level TB Outcomes in the United States</a>
<div class='details'>
Swartwood NA, <b>Testa C</b> Cohen T, Marks SM, Hill AN, Beeler-Assay G, Cochran J, Cranston K, Randall LM, Tibbs A, Horsburgh CR, Salomon JA, Menzies NA. BMC Medicine.
</div>

<a href="">The contribution of latent TB treatment to TB prevention in the United States: results of a transmission dynamic model</a>
<div class='details'>
Swartwood NA, <b>Testa C</b> Cohen T, Marks SM, Hill AN, Beeler-Assay G, Cochran J, Cranston K, Randall LM, Tibbs A, Horsburgh CR, Salomon JA, Menzies NA. 
</div>


<h4>2022</h4>

<a href="https://www.sciencedirect.com/science/article/pii/S2667193X22002010">
Relationship of political ideology of US federal and state elected officials and key COVID pandemic outcomes following vaccine rollout to adults: April 2021–March 2022
</a>
<div class='details'>
Krieger N, <b>Testa C</b>, Chen JT, Hanage WP, McGregor AJ. The Lancet Regional Health — Americas.
</div>

<a href="https://www.sciencedirect.com/science/article/pii/S2667193X22001818">
Estimated costs and quality-adjusted life-years lost due to N. gonorrhoeae infections acquired in 2015 in the United States: A modelling study of overall burden and disparities by age, race/ethnicity, and other factors
</a>
<div class='details'>
Li Y, Rönn MM, Tuite AR, Chesson HW, Gift TL, Trikalinos TA, <b>Testa C</b>, Bellerose M, Hsu K, Berruti AA, Malyuta Y, Menzies NA, Salomon JA. The Lancet Regional Health — Americas.
</div>

<a href="https://phdgp.github.io/PHDGP2.0/index.html">
The Public Health Disparities Geocoding Project 2.0 Training Manual
</a>
<div class='details'>
<b>Testa C</b>, Chen JT, Hall E, Javadi D, Morgan J, Rushovich T, Saha S, Waterman PD, Krieger N.
</div>

<a href="https://osf.io/preprints/rj79d/">
Epigenetic clocks and research implications of the lack of data on whom they have been developed: a review of reported and missing sociodemographic characteristics
</a>
<div class='details'>
Watkins SH, <b>Testa C</b>, Chen JT, De Vivo I, Simpkin AJ, Tilling K, Diez Roux AV, Davey Smith G, Waterman PD, Suderman M, Relton CL, Krieger N. OSF Preprints.
</div>


<a href="https://www.tandfonline.com/doi/full/10.1080/15592294.2022.2123898">
 The impact of low input DNA on the reliability of DNA methylation as measured by the Illumina Infinium MethylationEPIC BeadChip
</a>
<div class='details'>
Watkins SH, Ho K, <b>Testa C</b>, Falk L, Soul P, Nguyen LV, FitzGibbon S, Slack C, Chen JT, Davey Smith G, De Vivo I, Simpkin AJ, Tilling K, Waterman PD, Krieger N, Suderman M, Relton C. Epigenetics.
</div>

<a href="https://link.springer.com/article/10.1007/s40615-022-01353-z">
Using Implicit Measures of Discrimination: White, Black, and Hispanic Participants Respond Differently to Group-Specific Racial/Ethnic Categories vs. the General Category “People of Color” in the USA
</a>
<div class='details'>
Marini M, Waterman PD, Breedlove ER, Chen JT, <b>Testa C</b>, Pardee DJ, LeBlanc M, Reisner SL, Oendari A, Krieger N. Journal of Racial and Ethnic Health Disparities.
</div>

<a href="https://academic.oup.com/jncics/article/6/2/pkac016/6531976">
Breast Cancer Incidence, Hormone Receptor Status, Historical Redlining, and Current Neighborhood Characteristics in Massachusetts, 2005-2015 
</a>
<div class='details'>
Wright E, Waterman PD, Testa C, Chen JT, Krieger N. JNCI Cancer Spectrum.
</div>


<h4>2021</h4>



<a href="https://journals.lww.com/stdjournal/Abstract/9000/Modeling_the_Cost_Effectiveness_of_Express.97664.aspx">
Modeling the Cost-Effectiveness of Express Multi-Site Gonorrhea Screening among Men Who Have Sex with Men in the United States
</a>
<div class='details'>
Earnest R, Rönn MM, Bellerose M, Menon-Johansson AS, Berruti AA, Chesson HW, Gift TL, Hsu KK, <b>Testa C</b>, Zhu L, Malyuta Y, Menzies NA, Salomon JA. Sexually Transmitted Diseases.
</div>


<a href="https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)00465-7/fulltext">
Missing again: US racial and ethnic data for COVID-19 vaccination
</a>
<div class='details'>
Krieger N, Waterman PD, Chen JT, <b>Testa C</b>, Hanage WP. The Lancet.
</div>


<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/2623/2021/10/21_Krieger-et-al_regional-heterogeneity_Vol-21_No-6_with-tables-and-figures_rev-2.pdf">
Regional heterogeneity in COVID-19 risk in the United States during
the time of Delta (July 1 – September 15, 2021): The US south suffers
the highest case and death rates and greatest inequities
</a>
<div class='details'>
Krieger N, Chen JT, <b>Testa C</b>, Waterman PD, Hanage WP. HCPDS Working Paper Series.
</div>

<a href="https://link.springer.com/article/10.1007/s10654-020-00689-2">
COVID-19: US federal accountability for entry, spread, and inequities—lessons for the future
</a>
<div class='details'>
Hanage WP, <b>Testa C</b>, Chen JT, Davis L, Pechter E, Seminario P, Santillana M, 
Krieger N. European Journal of Epidemiology.
</div>

<a href="https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)32220-0/fulltext">
US racial and ethnic data for COVID-19 cases: still missing in action
</a>
<div class='details'>
Krieger N, <b>Testa C</b>, Hanage WP, Chen JT. The Lancet.
</div>

<a href="https://journals.lww.com/epidem/Fulltext/2021/01000/Time_Since_Infection_and_Risks_of_Future_Disease.10.aspx">
Time Since Infection and Risks of Future Disease for Individuals with
Mycobacterium tuberculosis Infection in the United States
</a>
<div class='details'>
Menzies NA, Swartwood N, <b>Testa C</b>, Malyuta Y, Hill AN, Marks SM, Cohen T, Salmon JA. Epidemiology.
</div>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/2623/2021/08/21_C19_vaxxvisual_pop-center-working-paper_chen-et-al_submitted_0808_with-cover-and-abstract_final.pdf">
Picturing prevention: Visualizing how vaccination profoundly protects
your loved ones, you, and your community from
hospitalization and death due to Covid- 19 using real-life
data from 12 US states (January – July 2021)
</a>
<div class='details'>
Chen JT, <b>Testa C</b>, Hanage WP, Krieger N. HCPDS Working Paper Series.
</div>

<a href="https://ascopubs.org/doi/abs/10.1200/JCO.2021.39.15_suppl.6543">
COVID-19 and exacerbation of screening mammography inequities.
</a>
<div class='details'>
Wang GX, Chen JT, Lamb L, <b>Testa C</b>, Waterman PD, Lehman CD, Krieger N. Journal of Clinical Oncology, Meeting Abstract.
</div>


<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2021/02/21_Chen_covidMortality_Race_Education_HCPDS_WorkingPaper_Vol-21_No-3_Final_footer.pdf">
Intersectional inequities in COVID-19 mortality by race/ethnicity and
education in the United States, January 1, 2020–January 31, 2021
</a>
<div class='details'>
Chen JT, <b>Testa C</b>, Waterman PD, Krieger N. HCPDS Working Paper Series.
</div>

<a href="https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-021-10171-7">
The target/perpetrator brief-implicit association test (B-IAT): an implicit instrument for efficiently measuring discrimination based on race/ethnicity, sex, gender identity, sexual orientation, weight, and age
</a>
<div class='details'>
Maddalena M, Waterman PD, Breedlove E, Chen JT, <b>Testa C</b>, Reisner SL, Pardee DJ, Mayer KHand Krieger N. BMC Public Health.
</div>

<h4>2020</h4>

<a href="https://journals.lww.com/stdjournal/Fulltext/2020/12000/Exploring_How_Epidemic_Context_Influences_Syphilis.3.aspx"> 
Exploring How Epidemic Context Influences Syphilis Screening Impact: A
Mathematical Modeling Study</a>
<div class='details'>
Tuite AR<sup>†</sup>, <b>Testa C</b><sup>†</sup>, Rönn MM, Bellerose M, Gift T,
Fridge J, Molotnikov L, Desmarais C, Berruti Andrés, Menzies N, Malyuta Y, Hsu
K, Salomon JA. Sexually Transmitted Diseases. <sup>†</sup>Contributed equally.
</div>

<a href="https://www.atsjournals.org/doi/10.1164/rccm.202003-0526OC">
Impact of effective global tuberculosis control on health and economic outcomes in the United States
</a>
<div class='details'>
Menzies NA, Bellerose M, <b>Testa C</b>, Swartwood N, Malyuta Y, Cohen T, Marks SM,
Hill AN, Date AA, Maloney SA, Bowden SE, Grills AW, Salomon JA. American
Journal of Respiratory and Critical Care Medicine.
</div>

<a href="https://journals.lww.com/stdjournal/Fulltext/2020/03000/The_Potential_Population_Level_Impact_of_Different.1.aspx">
The Potential Population-Level Impact of Different Gonorrhea Screening Strategies in Baltimore and San Francisco: An Exploratory Mathematical Modeling Analysis
</a>
<div class='details'>
Rönn MM<sup>†</sup>, <b>Testa C</b><sup>†</sup>, Tuite AR, Chesson HW, Gift TL, Schumacher C, Williford SL, Zhu L, Bellerose M, Earnest R, Malyuta Y, Hsu KK, Salomon JA, Menzies NA. Sexually Transmitted Diseases. <sup>†</sup>Contributed equally.
</div>

<a href="https://journals.lww.com/stdjournal/Abstract/2020/07000/Population_level_Benefits_of_Extragenital.12.aspx">
Population-level Benefits of Extragenital Gonorrhea Screening Among Men Who Have Sex With Men: An Exploratory Modeling Analysis
</a>
<div class='details'>
Earnest R, Rönn MM, Bellerose M, Gift T, Berruti AA, Hsu KK, <b>Testa C</b>, 
Zhu L, Malyuta Y, Menzies NA, Salomon JA. Sexually Transmitted Diseases.
</div>


# Press
<hr>

<div> 

<a href="https://www.nydailynews.com/opinion/ny-oped-why-we-must-go-big-on-relief-20210217-jqpvsicyqrdy5hdeqxcc4rg5ya-story.html">
Attack America’s overlapping miseries: Why going big on relief is an economic,
public health and moral imperative
</a>
<div class='details'>
This opinion piece we (Nancy Krieger, Christian Testa, Pamela Waterman and
Jarvis Chen) published in the New York Daily News presents a data driven
perspective on the concurrent tragedies of economic insecurity and COVID-19. We 
argue that federal relief addressing both of these needs is urgently necessary.
</div>

<a href="https://www.huffpost.com/entry/workers-blew-the-whistle-on-covid-hazards-then-people-died_n_5f80c1f8c5b62f97bac26e6e?guccounter=1">
Workers Tried To Blow The Whistle On COVID Hazards. Then People Died.
</a>
<div class='details'>
This article by Dave Jamieson in the HuffPost featured our work which showed that 
COVID-19 cases and deaths were consistently preceded by complaints filed with 
the Occupational Safety and Health Administration (OSHA). 
</div>

</div>

# Working Papers
<hr>

<div>
<h4>2021</h4>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2021/02/21_Chen_covidMortality_Race_Education_HCPDS_WorkingPaper_Vol-21_No-3_Final_footer.pdf">
Intersectional inequities in COVID-19 mortality by race/ethnicity and education in the United States, January 1, 2020–January 31, 2021
</a>
<div class='details'>
Chen JT, <b>Testa C</b>, Waterman PD, Krieger N.
</div>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2021/02/21_krieger-et-al_C19HH-pulse_HCPDS_Vol-21_No-2_Final.pdf">
Go big on relief! – repairing the commingled miseries of COVID-19 and US housing and food insecurity
</a>
<div class='details'>
Krieger N, <b>Testa C</b>, Waterman PD, Chen JT.
</div>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2021/02/21_Krieger_Waterman-et-al_missing-data-on-race-continues-w_-vaccine_HCPDS-Vol-21_No-1_FINAL_AB.pdf">
Plague of US missing COVID-19 data for race/ethnicity: Debacle continues with vaccination data
</a>
<div class='details'>
Krieger N, Waterman PD, Chen JT, <b>Testa C</b>, Santillana M, Hanage WP. HCPDS Working Paper Series.
</div>


<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/2623/2021/10/21_krieger-et-al_C19_political-lean-plus_HCPDS-working-paper_Vol-21_No-5_reduced-file-size.pdf">
Political lean: A crucial variable for monitoring COVID-19 in the United States
</a>
<div class='details'>
Krieger N, Chen JT, <b>Testa C</b>, Waterman PD, Hangae WP. HCPDS Working Paper Series.
</div>


<h4>2020</h4>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2020/12/20_Krieger-et-al_equity-in-vaccine-distribution_Volume-20_No-_5_final.pdf">
Warning against using static US county-level community data to guide equity in COVID-19 vaccine distribution: Temporal and spatial correlations of community characteristics with COVID-19 cases and deaths vary enormously and are increasingly uninformative
</a>
<div class='details'>
Krieger N, <b>Testa C</b>, Chen JT, Waterman PD, Hanage WP.
</div>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2020/10/changing-political-geographies-HCPDS-working-paper-volume-20-number-3-FINAL.pdf">
The changing political geographies of COVID-19 in the US
</a>
<div class='details'>
Krieger N, Chen JT, <b>Testa C</b>, Hanage WP.
</div>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2020/10/20_covid-19_federal-response_FINAL_for-HCPDS_1001_HCPDS-working-paper_volume-20_number-2_FINAL_corrected-affiliation.pdf">
COVID-19: US Federal accountability for entry, spread, and inequities
</a>
<div class='details'>
Hanage WP, <b>Testa C</b>, Chen JT, Davis L, Pechter E, Santillana M, Krieger N.
</div>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2020/09/20_krieger-et-al_covid-19-and-missing-data-on-race_ethnicity_final_Vol-20_No-1_with-supplemental-material.pdf">
US racial/ethnic data for COVID-19 cases: Still missing-in-action
</a>
<div class="details">
Krieger N, <b>Testa C</b>, Chen JT.
</div>

<a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2020/07/HCPDS-WP_19_4_testa-et-al_Visualizing-Lagged-Connection-Between-COVID-19-Cases-and-Deaths-in-US_final_07_10_with-cover.pdf">
Visualizing the lagged connection between COVID-19 cases and deaths in the United States: An animation using per capita state-level data (January 22, 2020 – July 8, 2020)
</a>
<div class='details'>
<b>Testa C</b>, Krieger N, Chen JT, Hanage WP.
</div>

<a href="https://www.medrxiv.org/content/10.1101/2020.04.06.20052506v1">
Defining high-value information for COVID-19 decision-making
</a>
<div class='details'>
Bilinski A, Birger R, Burn S, Chitwood M, Clarke-Deelder E, Copple T, Eaton J,
Ehrlich H, Erlendsdottir M, Eshghi S, Farid M, Fitzpatrick M, Giardina J,
Gonsalves G, Hsieh YL, Iloglu S, Kao Y, MacKay E, Menzies NA, Mulaney B,
Paltiel D, Perniciaro S, Phillips M, Rich K, Salomon JA, Sherak R, Shioda K,
Swartwood N, <b>Testa C</b>, Thornhill T, White E, Williamson A, York A, Zhu J, Zhu L. medRxiv. Authors in alphabetical order.
</div>

</div>


# Conference Posters
<hr>

<div>

<h4>2019</h4>

<a href="http://www.tbcontrollers.org/docs/posters-2019/79_Smartwood_Tabby2.pdf">
A User Friendly Web Tool for Exploring Future State-Level TB Outcomes for
User-Specified Scenarios
</a>
<div class='details'>
<b>Testa C</b>, Swartwood NA, Cohen T, Marks SM, Hill AN, Cochran J, Cranston K, Randall LM,
Tibbs A, Salomon JA, Menzies NA. National TB Controllers Association Conference. Awarded 2nd place in the poster competition.
</div>

<a href="http://www.tbcontrollers.org/docs/posters-2019/75.Smartwood.MITUS.pdf">
Modeling Interventions for TB in the United States: a flexible framework for modelling TB epidemiology and policy effects
</a>
<div class='details'>
Swartwood NA, <b>Testa C</b>, Cohen T, Marks SM, Hill AN, Cochran J, Cranston K, Randall LM,
Tibbs A, Salomon JA, Menzies NA. National TB Controllers Association Conference. 
</div>

Potential benefits of screening for gonorrhea in two urban centers: exploratory mathematical
modeling analysis
<div class='details'>
Rönn MM<sup>†</sup>, <b>Testa C</b><sup>†</sup>, Tuite AR, Gift TL, Chesson HW, Schumacher
C, Humes E, Menzies NA, Earnest R, Bellerose M, Malyuta Y, Hsu K, Salomon JA. STD Prevention Conference. <sup>†</sup>Contributed equally. 
</div>



</div>
